### ISSUE TITLE
Romanos 1:3

### ISSUE THREAD

**Issue by laboralissues** [BibliaJFAAL/JFAAL#3]
Olá! Há um acréscimo indevido no final do versiculo. O link para exegese também está inacessível

**Comment by marcoscaf** [comment]
Olá boa boa, a paz.
No github é somente a Bíblia.
Todo restante do conteúdo é privado.

Muito obrigado pelo feedback, vamos fazer essa correção (Romanos 1:3) ainda essa semana.

Att.

Marcos

Em ter., 1 de out. de 2024, 18:18, laboralissues ***@***.***>
escreveu:

**Comment by BibliaJFAAL** [comment]
Corrigino 01/10/2024 às 20:50
