### ISSUE TITLE
Erro de digitacao

### ISSUE THREAD

**Issue by laboralissues** [BibliaJFAAL/JFAAL#4]
![Screenshot_2024-10-01-18-21-49-259_com labmcs bibliastrong-edit](https://github.com/user-attachments/assets/a72cbd80-6b6b-4f5d-acae-6ba0acab0175)

**Comment by marcoscaf** [comment]
O conteúdo da exegese não está disponível no github. É somente a Bíblia JFAAL.

Vamos realizar a correção no app entre hoje e amanhã. 
Muito obrigado pelo feedback.

**Comment by marcoscaf** [comment]
O conteúdo da exegese não está disponível no github. É somente a Bíblia JFAAL.

Vamos realizar a correção direto no app entre hoje e amanhã.
Muito obrigado pelo feedback.
